name: Generate PDF Report

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
      - 'scripts/**'
      - 'README.md'
      - '.github/workflows/generate-pdf.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies for WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpango-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            libcairo2

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert jupyter weasyprint

      - name: Generate PDFs
        run: |
          echo "📄 Starting PDF generation..."
          python scripts/export_pdf.py
          echo "✅ PDF generation step finished."

      - name: Upload generated PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-reports
          path: reports/*.pdf

      - name: Commit PDFs back to repo (if changed)
        run: |
          echo "🔄 Preparing to commit PDFs..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git add reports/*.pdf
          git commit -m "Auto-update PDFs [skip ci]" || echo "⚠️ No PDF changes to commit."
          git push origin main --force
          echo "🚀 PDFs updated & pushed!"